limit_req_zone $binary_remote_addr zone=application_rate_limit:10m rate=3r/s;
limit_req_status 429;
# 3 reqs per second, since we have 3 containers running
# https://nginx.org/en/docs/http/ngx_http_limit_req_module.html
# TODO: Understand states
upstream rails_cluster {
    server application:3000 max_fails=3 fail_timeout=30s; ##  failover
    }
    # intuitively, you might ask why do we have to do this?
    # since all the 3 instances of the app have the same ip/dns/wtever it is
    # however, they have the same hostname, but not the same internal ip
    # without the upstream block, nginx, checks for the ip only once and uses that through out, now
    # however, it calls and chooses a random one each time
    # source, asked gemini
server {
    listen 80;
    listen [::]:80; # for ipv6 compatibility
    listen 443;
    listen [::]:443;
    server_name localhost;

    # reverse proxy

    location / {
        limit_req zone=application_rate_limit burst=10 nodelay;
        proxy_pass http://rails_cluster; # docker's internal naming dns wtver"
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    listen [::]:80; # for ipv6 compatibility
    listen 443;
    listen [::]:443;
    server_name grafana.localhost;

    auth_basic "Grafana - Auth";
    auth_basic_user_file /etc/nginx/.htpasswd; 

    location / {
        proxy_pass http://grafana:3000; # docker's internal naming dns wtver"
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}

server {
    listen 80;
    listen [::]:80; # for ipv6 compatibility
    listen 443;
    listen [::]:443;
    server_name prometheus.localhost;


    auth_basic "Prometheus - Auth";
    auth_basic_user_file /etc/nginx/.htpasswd; 


    location / {
        proxy_pass http://prometheus:9090; # docker's internal naming dns wtver"
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}