services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT # https://docs.docker.com/compose/support-and-feedback/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop
    env_file: .env
    networks:
      - application
      - storage
    expose:
      - "3000"
    volumes:
    - .:/app
    - /app/tmp/pids
    - nfs_shared:/shared  
    deploy:
      replicas: 3
    depends_on:
      - database

  database:
    image: mysql
    restart: always # always restart if something happens
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - application
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql # volume mapping

  guardian: #nginx
    image: nginx:alpine
    networks:
      - external
      - application
    ports:
      - "80:80"
      - "443:443" # for https
    volumes:
      - ./custom-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      application:
        condition: service_started
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    restart: always
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - application
      - monitoring
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    expose:
      - "9090"
    healthcheck:
          # Pings the built-in healthy endpoint. If it fails, it returns exit code 1.
          test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:9090/-/healthy || exit 1"]
          interval: 10s    # How often to check
          timeout: 5s      # How long to wait for a response
          retries: 5       # How many times to fail before marking it "unhealthy"
          start_period: 5s # Give the container a few seconds to boot before checking
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    healthcheck:
          test: ["CMD-SHELL", "wget -q --tries=1 --spider http://localhost:3000/api/health || exit 1"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 5s
    expose:
      - "3000"
    networks:
      - application
      - monitoring
    restart: unless-stopped
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources/
    depends_on:
      - prometheus
# https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/compose.yaml

  nfs:
  image: itst/nfs-server:latest    
  container_name: nfs
  privileged: true               
  environment:
    SHARED_DIRECTORY: /export
    EXPORT_OPTIONS: "(rw,sync,no_subtree_check,no_root_squash)"
  volumes:
    - nfs_data:/export
  restart: always
  newtorks:
    - storage


volumes:
  mysql_data:
  prom_data:
  nfs_shared:
    driver_opts:
      type: nfs
      o: addr=nfs,vers=4,ro=0 #mount options
      device: ":/export"

networks:
  external:
  application:
  monitoring: